[project]
name = "academix_pro"
version = "1.0.0"
description = "Académix Pro - Tu Asistente y Calculadora Académica"
authors = [{ name = "Diego Muria", email = "diegomuria08@gmail.com" }]
dependencies = [
    "flet>=1.0.1",
    "httpx>=0.28.1",
]

[tool.flet]
org = "com.academix"
product = "Académix Pro"
company = "Diego Muria - IUPSM"
copyright = "Derechos reservados para Diego Muria estudiante de ingenieria de sistemas del IUPSM"
